version: "3.9"
x-build: &dockerfile-dev-build
  context: .
  dockerfile: Dockerfile.local
services:
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: Password1
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$$SA_PASSWORD" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5672:5672"
      - "15672:15672"
  
  common:
    build: *dockerfile-dev-build
    env_file: .env
    depends_on:
      sqlserver:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
#    volumes:
#      - "./:/app/"

  app:
    extends:
      service: common
    ports:
      - "5087:8080"
    entrypoint: [ "dotnet", "/app/src/AspnetTemplate.Api/bin/Debug/net7.0/AspnetTemplate.Api.dll" ]
    
  worker:
    extends:
      service: common
    ports:
      - "5087:8080"
    entrypoint: [ "dotnet", "/app/src/AspnetTemplate.Api/bin/Debug/net7.0/AspnetTemplate.Worker.dll", "--", "product.created"]

  test:
    extends:
      service: common
    entrypoint: [ "dotnet", "test" ]