FROM mcr.microsoft.com/dotnet/sdk:7.0

WORKDIR /app

COPY src/AspnetTemplate.Api/*.csproj ./src/AspnetTemplate.Api/
COPY src/AspnetTemplate.Core/*.csproj ./src/AspnetTemplate.Core/
COPY src/AspnetTemplate.Worker/*.csproj ./src/AspnetTemplate.Worker/
COPY tests/*.csproj ./tests/
COPY Directory.Build.props ./
COPY Directory.Packages.props ./
COPY *.sln ./
RUN dotnet restore

COPY . .
RUN dotnet build

RUN dotnet tool install --global dotnet-ef --version 7.0.14