version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: "Dockerfile"
    env_file: .env
    depends_on:
      sqlserver:
        condition: service_healthy
    ports:
      - "5087:80"
    entrypoint: ["dotnet", "AspnetTemplate.dll"]

  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: Password1
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "Password1" -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s